### ISSUE TITLE
`getChatEvents()` not export

### ISSUE THREAD

**Issue by inkydragon** [JuliaBerry/PiCraft.jl#35]
In docs, it mentioned `getChatEvents()` , but it has not been exported.

- [Events, Entities and Camera · PiCraft](https://juliaberry.github.io/PiCraft.jl/eventsEntitiesCamera/#Chat-Event-1)
 
```julia
julia> getChatEvents()
ERROR: UndefVarError: getChatEvents not defined
```

---

workaround

```
julia> PiCraft.getChatEvents()
0-element Array{Tuple{Int64,String},1}
```

**Comment by aviks** [comment]
@Ellipse0934 thoughts?

**Comment by Ellipse0934** [comment]
Thanks for reporting the issue.
